name: benchmarks run

on:
  workflow_dispatch:

permissions: read-all

jobs:
  e2e:
    name: End-to-end sign and verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      - run: |
          set -euo pipefail
          cd model_signing
          sudo apt -y install git git-lfs python3-venv python3-pip
          git lfs install
          bash benchmarks/run.sh https://github.com/login/oauth https://github.com/"$GITHUB_REPOSITORY"/.github/workflows/benchmarks.yml@refs/heads/main
