name: SLSA for ML models example
on:
  workflow_dispatch:
    inputs:
      model_type:
        description: Name of the model (implies framework)
        required: true
        type: choice
        options:
        - tensorflow_model.keras
        - tensorflow_saved_model
        - tensorflow_exported_model
        - tensorflow_hdf5_model.h5
        - tensorflow_hdf5.weights.h5
        - pytorch_model.pth
        - pytorch_full_model.pth
        - pytorch_jitted_model.pt

permissions:
  contents: write

jobs:
  train:
    name: Train model and save as ${{ github.event.inputs.model_type }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: slsa_for_models/install/requirements.txt
    - name: Install dependencies
      run: |
        set -euo pipefail
        python -m venv venv
        source venv/bin/activate
        python -m pip install --require-hashes -r slsa_for_models/install/requirements.txt
    - name: Build model
      env:
        MODEL_TYPE: ${{ github.event.inputs.model_type }}
      run: |
        set -euo pipefail
        source venv/bin/activate
        python slsa_for_models/main.py "$MODEL_TYPE"
    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        path: ${{ github.event.inputs.model_type }}
        name: ${{ github.event.inputs.model_type }}
        if-no-files-found: error
