name: Run unit tests
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  model-signing-unit-tests:
    name: Run unit tests for signing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: |
          model_signing/install/requirements_${{ runner.os }}.txt
          model_signing/install/requirements_test_${{ runner.os }}.txt
    - name: Install dependencies
      run: |
        set -euo pipefail
        bash .github/workflows/scripts/venv_setup.sh
        python -m pip install --require-hashes -r model_signing/install/requirements_${{ runner.os }}.txt
        python -m pip install --require-hashes -r model_signing/install/requirements_test_${{ runner.os }}.txt
    - name: Run unit tests
      run: |
        set -euo pipefail
        bash .github/workflows/scripts/venv_activate.sh
        # NOTE: option --full-trace may be useful for troubleshooting.
        # TODO(#68): Remove the need to create this folder.
        mkdir testdata
        pytest -v .