name: Validate all Python dependencies work together
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
      - '*.md'

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  model-signing:
    name: Test model signing dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: model_signing/install/requirements_${{ runner.os }}.txt
    - name: Install dependencies
      run: |
        set -exuo pipefail
        python -m venv venv
        .github/workflows/scripts/venv_activate.sh
        python -m pip install --require-hashes -r model_signing/install/requirements_${{ runner.os }}.txt

  slsa-for-ml:
    name: Test SLSA for ML demo dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: slsa_for_models/install/requirements_${{ runner.os }}.txt
    - name: Install dependencies
      run: |
        set -exuo pipefail
        python -m venv venv
        .github/workflows/scripts/venv_activate.sh
        python -m pip install --require-hashes -r slsa_for_models/install/requirements_${{ runner.os }}.txt
