name: Validate all Python dependencies work together
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  model-signing:
    name: Test model signing dependencies
    runs-on: ${RUNNER_OS}}
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: model_signing/install/requirements_${{ runner.os }}.txt
    - name: Install dependencies
      run: |
        set -euo pipefail
        bash .github/workflows/scripts/venv_setup.sh
        python -m pip install --require-hashes -r model_signing/install/requirements_${RUNNER_OS}}.txt

  slsa-for-ml:
    name: Test SLSA for ML demo dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: slsa_for_models/install/requirements_${{ runner.os }}.txt
    - name: Install dependencies
      run: |
        set -euo pipefail
        bash .github/workflows/scripts/venv_setup.sh
        python -m pip install --require-hashes -r slsa_for_models/install/requirements_${RUNNER_OS}}.txt
