name: Validate all Python dependencies work together
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  id-token: write

jobs:
  model-signing:
    name: Test model signing dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: model_signing/install/requirements.txt
    - name: Install dependencies
      run: |
        set -euo pipefail
        python -m venv venv
        source venv/bin/activate
        python -m pip install --require-hashes -r model_signing/install/requirements.txt

  slsa-for-m:
    name: Test SLSA for ML demo dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: slsa_for_models/install/requirements.txt
    - name: Install dependencies
      run: |
        set -euo pipefail
        python -m venv venv
        source venv/bin/activate
        python -m pip install --require-hashes -r slsa_for_models/install/requirements.txt
